<html>
    <script>
        const posts = [
            { title: 'Post One', body: 'This post is one'},
            { title: 'Post Two', body: 'This post is two'},     
        ];

        function getPost(){
            setTimeout(() => {
                let output = '';
                posts.forEach((post, index) => {
                    output += `<li> ${post.title} </li>`;
                });
                document.body.innerHTML = output;
            }, 1000);
        }

        function createPost(post){
            return new Promise((resolve, reject) =>{
                setTimeout(() =>{
                    posts.push(post);
                    const error = false;    //set true for display error

                    if(!error){
                        resolve();
                    }
                    else{
                        reject("Error: Something went wrong");
                    }
                }, 1000);
            });
        }

        function deletePost(){
            return new Promise((resolve, reject) =>{
                setTimeout(() =>{
                    //posts.pop();      
                    if(posts.length > 0){
                        resolve(posts.pop());
                    }
                    else{
                        reject('Error: Array is empty');
                    }
                }, 1000);
            });
        }

        // task 3 deleting one by one then showing error
        // createPost({title: 'Post Three', body:'This is post three'}).
        // then(() => {
        //     getPost(),
        //     deletePost().then(() =>{
        //         getPost(),
        //         deletePost().then(() =>{
        //             getPost(),
        //             deletePost().then(() =>{
        //                 getPost(),
        //                 deletePost().then(() =>{ }) 
        //                 .catch((err) => {
        //                     console.log(err);   
        //                 })
        //             })
        //         })
        //     })

        // }).catch( err =>  console.log(err));

        
        //task 4..continue  creating 4th post deleting after 1 sec show error

        createPost({title: 'Post Three', body:'This is post three'}).
        then(() => {
            getPost(),
            deletePost().then(() =>{
                getPost(),
                deletePost().then(() =>{
                    getPost(),
                    deletePost().then(() =>{
                        getPost(),
                        createPost({title: 'Post Four', body:'This is post four'}).then(()=>{
                            getPost()
                            deletePost().then(() =>{ 
                                getPost()
                                deletePost().then(() => {}).
                                catch((err) => {
                                    console.log(err);   
                                })
                            }) 
                        })  
                    })      
                })
            })

        })

    </script>

</html>
